version: '3.8'
services:
  client:
    environment:
      - BOND_ENV=sandbox.staging
      - SERVER_ENDPOINT=https://sandbox.staging.bond.tech/api/v0/accounts
      - ACCOUNT_ID=48bfae32-c1f6-42cc-ab42-fe6e50904d11
      - CYPRESS_BASE_URL=http://localhost:8080
      - CLIENT_ENDPOINT=http://localhost:8080
      - IDENTITY=${CYPRESS_IDENTITY}
      - AUTHORIZATION=${CYPRESS_AUTHORIZATION}

    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARTIFACTORY_USER: ${ARTIFACTORY_USER}
        ARTIFACTORY_API_KEY: ${ARTIFACTORY_API_KEY}
        ARTIFACTORY_PYPI_REPOSITORY: ${ARTIFACTORY_PYPI_REPOSITORY}
        ARTIFACTORY_URL: ${ARTIFACTORY_URL}
    container_name: bond-sdk-web-client
    restart: unless-stopped
    ports:
      - 8080:8080
