version: '3.8'
services:
  
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARTIFACTORY_USER: ${ARTIFACTORY_USER}
        ARTIFACTORY_API_KEY: ${ARTIFACTORY_API_KEY}
        ARTIFACTORY_PYPI_REPOSITORY: ${ARTIFACTORY_PYPI_REPOSITORY}
        ARTIFACTORY_URL: ${ARTIFACTORY_URL}
    environment:
      - BOND_ENV=sandbox
      - SERVER_ENDPOINT=https://sandbox.bond.tech/api/v0/accounts
      - CYPRESS_BASE_URL=http://localhost:8080
      - CLIENT_ENDPOINT=http://localhost:8080
      - IDENTITY=${CYPRESS_IDENTITY}
      - AUTHORIZATION=${CYPRESS_AUTHORIZATION}
      - ACCOUNT_ID=${CYPRESS_ACCOUNT_ID}
    ports:
      - 8080:8080
    restart: unless-stopped

  cypress:
    environment:
      # Cypress project
      - CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}
      # Application URLs
      - CYPRESS_BASE_URL=http://client:8080
      - CLIENT_ENDPOINT=http://client:8080
      # Studio access variables
      - CYPRESS_STUDIO_HOST=${CYPRESS_STUDIO_HOST}
      - CYPRESS_IDENTITY=${CYPRESS_IDENTITY}
      - CYPRESS_AUTHORIZATION=${CYPRESS_AUTHORIZATION}
      # Debit variables
      - CYPRESS_DEBIT_CUSTOMER_ID=${CYPRESS_CREDIT_CUSTOMER_ID}
      - CYPRESS_DEBIT_CARD_ID=${CYPRESS_DEBIT_CARD_ID}
      - CYPRESS_DEBIT_CARD_NUMBER=${CYPRESS_DEBIT_CARD_NUMBER}
      - CYPRESS_DEBIT_CARD_EXP=${CYPRESS_DEBIT_CARD_EXP}
      - CYPRESS_DEBIT_CARD_CVV=${CYPRESS_DEBIT_CARD_CVV}
      - CYPRESS_DEBIT_CARD_PIN=${CYPRESS_DEBIT_CARD_PIN}
      - CYPRESS_DEBIT_CARD_NEW_PIN=${CYPRESS_DEBIT_CARD_NEW_PIN}
      # Credit variables
      - CYPRESS_CREDIT_CUSTOMER_ID=${CYPRESS_CREDIT_CUSTOMER_ID}
      - CYPRESS_CREDIT_CARD_ID=${CYPRESS_CREDIT_CARD_ID}
      - CYPRESS_CREDIT_CARD_NUMBER=${CYPRESS_CREDIT_CARD_NUMBER}
      - CYPRESS_CREDIT_CARD_EXP=${CYPRESS_CREDIT_CARD_EXP}
      - CYPRESS_CREDIT_CARD_CVV=${CYPRESS_CREDIT_CARD_CVV}
      - CYPRESS_CREDIT_CARD_PIN=${CYPRESS_CREDIT_CARD_PIN}
      - CYPRESS_CREDIT_CARD_NEW_PIN=${CYPRESS_CREDIT_CARD_NEW_PIN}
      # Context info
      - COMMIT_INFO_MESSAGE=${COMMIT_INFO_MESSAGE}
      - COMMIT_INFO_BRANCH=${COMMIT_INFO_BRANCH}
      - COMMIT_INFO_AUTHOR=${COMMIT_INFO_AUTHOR}
      - COMMIT_INFO_SHA=${COMMIT_INFO_SHA}
      - COMMIT_INFO_REMOTE=${COMMIT_INFO_REMOTE}
      # Deprecated (I hope)
      - BOND_ENV=sandbox
      - SERVER_ENDPOINT=https://sandbox.bond.tech/api/v0/accounts
      - CUSTOMER_ID=${CYPRESS_CUSTOMER_ID}
      - ACCOUNT_ID=${CYPRESS_ACCOUNT_ID}
    build:
      context: .
      dockerfile: cypress.Dockerfile
      args:
        ARTIFACTORY_USER: ${ARTIFACTORY_USER}
        ARTIFACTORY_API_KEY: ${ARTIFACTORY_API_KEY}
        ARTIFACTORY_PYPI_REPOSITORY: ${ARTIFACTORY_PYPI_REPOSITORY}
        ARTIFACTORY_URL: ${ARTIFACTORY_URL}
    container_name: cypress
    restart: unless-stopped
    # extra_hosts:
    #   - 'bond-sdk-web-client:${SDK_CONTAINER_IP}'
