version: '3.8'
services:
  # Cypress container
  cypress:
    environment:
      - CYPRESS_BASE_URL=http://bond-sdk-web-client:8080
      - CLIENT_ENDPOINT=http://bond-sdk-web-client:8080
      - IDENTITY=${CYPRESS_IDENTITY}
      - AUTHORIZATION=${CYPRESS_AUTHORIZATION}
      - CYPRESS_CREDIT_CARD_ID=${CYPRESS_CREDIT_CARD_ID}
      - CYPRESS_CREDIT_CARD_NUMBER=${CYPRESS_CREDIT_CARD_NUMBER}
      - CYPRESS_CREDIT_CARD_EXP=${CYPRESS_CREDIT_CARD_EXP}
      - CYPRESS_CREDIT_CARD_CVV=${CYPRESS_CREDIT_CARD_CVV}
      - CYPRESS_CREDIT_CARD_PIN=${CYPRESS_CREDIT_CARD_PIN}
      - CYPRESS_CREDIT_CARD_NEW_PIN=${CYPRESS_CREDIT_CARD_NEW_PIN}
      - CYPRESS_DEBIT_CARD_ID=${CYPRESS_DEBIT_CARD_ID}
      - CYPRESS_DEBIT_CARD_NUMBER=${CYPRESS_DEBIT_CARD_NUMBER}
      - CYPRESS_DEBIT_CARD_EXP=${CYPRESS_DEBIT_CARD_EXP}
      - CYPRESS_DEBIT_CARD_CVV=${CYPRESS_DEBIT_CARD_CVV}
      - CYPRESS_DEBIT_CARD_PIN=${CYPRESS_DEBIT_CARD_PIN}
      - CYPRESS_DEBIT_CARD_NEW_PIN=${CYPRESS_DEBIT_CARD_NEW_PIN}
      - CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}
      - COMMIT_INFO_MESSAGE=${COMMIT_INFO_MESSAGE}
      - COMMIT_INFO_BRANCH=${COMMIT_INFO_BRANCH}
      - COMMIT_INFO_AUTHOR=${COMMIT_INFO_AUTHOR}
      - COMMIT_INFO_SHA=${COMMIT_INFO_SHA}
      - COMMIT_INFO_REMOTE=${COMMIT_INFO_REMOTE}
      - BOND_ENV=sandbox.staging
      - SERVER_ENDPOINT=https://sandbox.staging.bond.tech/api/v0/accounts
      - ACCOUNT_ID=c8ae0550-ac12-4269-a8ca-618f796350de
      - IDENTITY_FOR_EXTERNAL_ACCOUNTS_SDK=bb4a3d1f-d812-457e-ba5e-227cc62a1b15
      - AUTHORIZATION_FOR_EXTERNAL_ACCOUNTS_SDK=yRAsHYXDRv/pPwMj6i4/cumyWVERRiHPCMa/FQSQoMXfMg5CXsqr/q6s6irLdfSB
    build:
      context: .
      dockerfile: cypress.Dockerfile
      args:
        ARTIFACTORY_USER: ${ARTIFACTORY_USER}
        ARTIFACTORY_API_KEY: ${ARTIFACTORY_API_KEY}
        ARTIFACTORY_PYPI_REPOSITORY: ${ARTIFACTORY_PYPI_REPOSITORY}
        ARTIFACTORY_URL: ${ARTIFACTORY_URL}
    container_name: cypress
    restart: unless-stopped
    extra_hosts:
      - 'bond-sdk-web-client:${SDK_CONTAINER_IP}'
